title: VZW De Zwarte Arend Tennis Club
baseurl: ""
url: "https://zwartearend.github.io"
lang: nl
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    theme: 'pastie'    # Another solid light option
